### ISSUE TITLE
Exception in Web UI if navigator has less than 2 items enabled

### ISSUE THREAD

**Issue by samatary** [project-owner/Peppy#28]
If you enable only one or no item at all in the navigator, e.g.:
<details>
  <summary>config.txt</summary>

```
[...]
[home.navigator]
back = False
screensaver = False
equalizer = False
language = False
timer = False
network = False
player = True
about = False
[...]
```

</details>

Peppy freezes when you click the home-button. When you reload the webpage, an exception is thrown:
<details>
  <summary>peppy.log</summary>

```
[2022-09-06 10:41:49,904] {web.py:2243} INFO - 101 GET /ws (192.168.8.105) 1.98ms
[2022-09-06 10:41:49,905] {websockethandler.py:42} DEBUG - Added web client
[2022-09-06 10:41:49,925] {web.py:1793} ERROR - Uncaught exception GET /ws (192.168.8.105)
HTTPServerRequest(protocol='http', host='192.168.8.106:8000', method='GET', uri='/ws', version='HTTP/1.1', remote_ip='192.168.8.105')
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/tornado/websocket.py", line 647, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/pi/Peppy/web/server/handlers/websockethandler.py", line 48, in on_message
    self.handle_command(d)
  File "/home/pi/Peppy/web/server/handlers/websockethandler.py", line 68, in handle_command
    self.redraw_web_ui()
  File "/home/pi/Peppy/web/server/webserver.py", line 216, in redraw_web_ui
    self.send_json_to_web_ui(self.screen_to_json())
  File "/home/pi/Peppy/web/server/webserver.py", line 260, in screen_to_json
    return self.json_factory.screen_to_json(current_screen, screen)
  File "/home/pi/Peppy/web/server/jsonfactory.py", line 75, in screen_to_json
    components.extend(self.get_title_menu_screen_components(screen))
  File "/home/pi/Peppy/web/server/jsonfactory.py", line 140, in get_title_menu_screen_components
    if KEY_LOADING in components[first_loading_component]["name"]:
IndexError: list index out of range
[2022-09-06 10:41:49,935] {websockethandler.py:55} DEBUG - Removed web client

```

</details>

**Comment by project-owner** [comment]
Hi Sam, 

Thank you for reporting the issue. I'll fix it in the next release. The tentative date for the next release is October.

Regards

**Comment by project-owner** [comment]
The issue was fixed in the new release - Seurat Edition.
